# Generated by Django 4.0.4 on 2022-06-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicios_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='imagen',
        ),
    ]
