# Generated by Django 4.0.4 on 2022-06-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('mision', models.CharField(max_length=1000)),
                ('vision', models.CharField(max_length=1000)),
            ],
        ),
    ]
