# Generated by Django 4.0.4 on 2022-06-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sobrenosotros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nosotros',
            options={'verbose_name': 'Nosotro', 'verbose_name_plural': 'Nosotros'},
        ),
    ]
