# Generated by Django 4.0.4 on 2022-06-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='SKU',
            new_name='cod',
        ),
    ]
