# Generated by Django 4.0.4 on 2022-06-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_sku_products_cod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='activo',
            new_name='is_active',
        ),
    ]
